// Add this data structure based on your Excel file
    const kerjaData = {
      "BIBITAN INFRASTRUKTUR": [
        {kode: "PLIN01", kerja: "Imas"},
        {kode: "PLIN02", kerja: "Tumbang"},
        {kode: "PLIN03", kerja: "Memerun"},
        {kode: "PLIN04", kerja: "Pemberantasan Lalang"},
        {kode: "PAIN01", kerja: "Persiapan Areal"},
        {kode: "PAIN02", kerja: "Pemadatan Tapak tan (Gambut)"},
        {kode: "JPIN01", kerja: "Pancang rencana jalan"},
        {kode: "JPIN02", kerja: "Pancang rencana parit"},
        {kode: "JPIN03", kerja: "Buat Jalan Manual"},
        {kode: "JPIN04", kerja: "Buat Parit Manual"},
        {kode: "PGIN01", kerja: "Pemagaran"},
        {kode: "BGIN01", kerja: "Bangunan Barak-Kantor"},
        {kode: "BGIN02", kerja: "Bangunan Menara Control"},
        {kode: "BGIN03", kerja: "Bangunan rumah pompa air"},
        {kode: "IAIN01", kerja: "Pancang rencana instalasi pipa"},
        {kode: "IAIN02", kerja: "Gali jalur pipa"},
        {kode: "IAIN03", kerja: "Pasang instalasi pipa"},
        {kode: "IAIN04", kerja: "Pasang pompa air"},
        {kode: "MDIN01", kerja: "Pengawasan tan"},
        {kode: "TRIN01", kerja: "Traktor - Prasarana INtn"},
        {kode: "TRIN02", kerja: "Truk - Prasarana INtn"},
        {kode: "TRIN03", kerja: "Kendaraan Transportasi"},
        {kode: "TRIN05", kerja: "Alat Berat - Jalan/parit INtn"},
        {kode: "TRIN06", kerja: "Truk - Jalan/parit INtn"},
        {kode: "TRIN07", kerja: "Excavator - Jalan/parit INtn"},
        {kode: "TRIN08", kerja: "Road Grader - Jalan/parit INtn"},
        {kode: "TRIN09", kerja: "Bulldozer - Jalan/parit INtn"},
        {kode: "TRIN11", kerja: "Alat Berat - Perataan tan"},
        {kode: "TRIN12", kerja: "Truk - Perataan tanah"}
      ],
      "BIBITAN PRE-NURSERY": [
        {kode: "BPPN01", kerja: "Kumpul & Ayak Tanah"},
        {kode: "BPPN02", kerja: "Capur Tanah dengan Pupuk"},
        {kode: "BPPN03", kerja: "Isi Tanah ke Pbag"},
        {kode: "BPPN04", kerja: "Buat Bedengan"},
        {kode: "BPPN05", kerja: "Susun Pbag di Bedengan"},
        {kode: "BPPN06", kerja: "Fumigasi"},
        {kode: "PUPN01", kerja: "Pupuk pelet"},
        {kode: "PUPN02", kerja: "Pupuk butiran"},
        {kode: "PUPN03", kerja: "Semprot pupuk daun"},
        {kode: "PUPN04", kerja: "Semprot hormon daun"},
        {kode: "HPPN01", kerja: "Pasang umpan racun tikus"},
        {kode: "HPPN02", kerja: "Semprot insektisida"},
        {kode: "HPPN03", kerja: "Semprot Fungisida"},
        {kode: "KCPN01", kerja: "Tanam Kecambah"},
        {kode: "KCPN02", kerja: "Buat Naungan Bedengan"},
        {kode: "KCPN03", kerja: "Tulis Identitas Polybag"},
        {kode: "KCPN04", kerja: "Konsol Tanah Pbag di Bedengan"},
        {kode: "SRPN01", kerja: "Menyiram"},
        {kode: "MOPN01", kerja: "Konsol tanah Pbag di bedengan"},
        {kode: "MOPN02", kerja: "Merumput di Pbag"},
        {kode: "MOPN03", kerja: "Merumput diluar Pbag"},
        {kode: "MOPN04", kerja: "Atur naungan bedengan"},
        {kode: "MOPN05", kerja: "Beri mulsa pada Pbag"},
        {kode: "MOPN06", kerja: "Pengumpulan Baby & Large Polybag"},
        {kode: "MOPN07", kerja: "Bloking Media Tanam"},
        {kode: "SKPN01", kerja: "Afkir Kecambah abnormal"},
        {kode: "TRPN01", kerja: "Traktor TrnsKaryawan"},
        {kode: "TRPN02", kerja: "A.Berat kumpul tanah Baby Polybag"}
      ],
      "BIBITAN MAIN-NURSERY": [
        {kode: "MOMN01", kerja: "Merumput di dalam Pbag"},
        {kode: "MOMN02", kerja: "Merumput di luar Pbag"},
        {kode: "MOMN03", kerja: "Semprot rumput di luar poybag"},
        {kode: "MOMN04", kerja: "Konsol tanah diPbag"},
        {kode: "MOMN05", kerja: "Pemberian mulsa di Pbag"},
        {kode: "MOMN06", kerja: "Konsol Pbag"},
        {kode: "MOMN07", kerja: "Putar t"},
        {kode: "MOMN08", kerja: "Ikat daun t"},
        {kode: "MOMN09", kerja: "Pangkas daun t"},
        {kode: "MOMN10", kerja: "Langsir Baby Pbag"},
        {kode: "MOMN11", kerja: "Langsi Large Pbag"},
        {kode: "MOMN12", kerja: "Pengumpulan Baby & Large Polybag"},
        {kode: "SRMN01", kerja: "Siram Upah"},
        {kode: "PUMN01", kerja: "Pupuk kaplet"},
        {kode: "PUMN02", kerja: "Pupuk butiran"},
        {kode: "PUMN03", kerja: "Semprot pupuk daun"},
        {kode: "PUMN04", kerja: "Semprot hormon daun"},
        {kode: "PUMN05", kerja: "Bongkar Muat Pupuk"},
        {kode: "HPMN01", kerja: "Pasang umpan racun tikus"},
        {kode: "HPMN02", kerja: "Semprot insektisida"},
        {kode: "HPMN03", kerja: "Kutib ulat daun"},
        {kode: "HPMN04", kerja: "Semprot Fungisida"},
        {kode: "SKMN01", kerja: "Afkir t abnormal"},
        {kode: "MDMN01", kerja: "By. mandor"},
        {kode: "MDMN02", kerja: "By. penjagaan tan"},
        {kode: "JRMN01", kerja: "Kumpul & ayak tanah"},
        {kode: "JRMN02", kerja: "Campur tanah dengan pupuk"},
        {kode: "JRMN03", kerja: "Isi tanah ke Pbag"},
        {kode: "JRMN04", kerja: "Memancang barisan Pbag"},
        {kode: "JRMN05", kerja: "Susun Pbag pada barisan"},
        {kode: "JRMN06", kerja: "Konsol tanah Pbag"},
        {kode: "JRMN07", kerja: "Buat lobang di Pbag"},
        {kode: "JRMN08", kerja: "Ecer t baby"},
        {kode: "JRMN09", kerja: "Tanam aquasorb"},
        {kode: "JRMN10", kerja: "Tanam t"},
        {kode: "JRMN11", kerja: "Tulis identitas batch"},
        {kode: "JRMN12", kerja: "Siapkan Large Polybag"},
        {kode: "TRMN01", kerja: "Traktor - Tranportasi"},
        {kode: "TRMN02", kerja: "Truk - Tranportasi"},
        {kode: "TRMN03", kerja: "Alat Berat - Pelihalokasi"},
        {kode: "TRMN04", kerja: "Truk TrnsKaryawan"},
        {kode: "TRMN05", kerja: "Kend. - Tranportasi"},
        {kode: "TRMN06", kerja: "Siram By. Mesin Pompa Air"},
        {kode: "TRMN07", kerja: "Traktor - Tranplanting"},
        {kode: "TRMN08", kerja: "Truk - Tranplanting"},
        {kode: "TRMN09", kerja: "Alat Berat Transplanting"},
        {kode: "INPN01", kerja: "Pelihara instalasi air Upah"},
        {kode: "INPN02", kerja: "Pelihara jalan Upah"},
        {kode: "INPN03", kerja: "Pelihara parit Upah"}
      ],
      "LAND CLEARING": [
        {kode: "LCKT01", kerja: "Buat tapak kuda"},
        {kode: "LCKT02", kerja: "Pancang rencana teras contour"},
        {kode: "LCKT03", kerja: "Buat teras contour"},
        {kode: "LCKT04", kerja: "Jaga alat berat di lapangan"},
        {kode: "LCSU01", kerja: "Survey Intern"},
        {kode: "LCSU02", kerja: "Survey Ekstern"},
        {kode: "LCRT01", kerja: "Buat tanda-tanda batas"},
        {kode: "LCRT02", kerja: "Merintis bloking rencana areal"},
        {kode: "LCIM01", kerja: "Imas"},
        {kode: "LCTU01", kerja: "Tumbang"},
        {kode: "LCTU02", kerja: "Racun pokok"},
        {kode: "LCTU03", kerja: "Chipper Mekanis"},
        {kode: "LCTU04", kerja: "Enviro Mulcher"},
        {kode: "LCCI01", kerja: "Cincang Perun"},
        {kode: "LCCI02", kerja: "Pancang Jalur Mekanis"},
        {kode: "LCCI03", kerja: "Perun / rumpuk mekanis"},
        {kode: "LCBK01", kerja: "Buat Blok"},
        {kode: "LCBT01", kerja: "Keamanan alat berat - Bajak"},
        {kode: "LCBT02", kerja: "Bersihkan sisa tidak kena bajak"},
        {kode: "LCGT01", kerja: "Keamanan alat berat - Garu"},
        {kode: "LCLL01", kerja: "Semprot lalang I"},
        {kode: "LCLL02", kerja: "Semprot lalang II"},
        {kode: "LCLL03", kerja: "Wiping lalang I"},
        {kode: "LCLL04", kerja: "Wiping lalang II"},
        {kode: "LCLL05", kerja: "Semprot gawangan"},
        {kode: "LCMD01", kerja: "Pengawasan/MANDOR"},
        {kode: "LCJJ01", kerja: "Pembuatan Jalan / Jembatan"},
        {kode: "LCJJ02", kerja: "Pancang Jalan Kontur"},
        {kode: "LCPR01", kerja: "Pembuatan Parit"},
        {kode: "LCTR01", kerja: "Alokasi Traktor Angkut Karyawan"},
        {kode: "LCTR02", kerja: "Alokasi Truk Angkut Karyawan'"},
        {kode: "LCTR03", kerja: "Alokasi Traktor Angkut Material/Pupuk"},
        {kode: "LCTR04", kerja: "Alokasi Truk Angkut Material Pupuk"},
        {kode: "LCTR05", kerja: "Alokasi Kendaraaan Umum Angkut Karyawan"},
        {kode: "LCTR06", kerja: "Alokasi Kendaraan Umum Angkut Material/Pupuk"},
        {kode: "LCTR07", kerja: "Alokasi Traktor - Garu Tanah"},
        {kode: "LCTR08", kerja: "Alokasi Truk - Transportasi Garu"},
        {kode: "LCTR09", kerja: "Alokasi Harrower - Garu Tanah"},
        {kode: "LCTR10", kerja: "Alokasi Bulldozer - Garu Tanah"},
        {kode: "LCTR11", kerja: "Alokasi Traktor - Transportasi Garu"},
        {kode: "LCTR12", kerja: "Alokasi Buldozer - Perbaikan Jalan"},
        {kode: "LCTR13", kerja: "Alokasi Alat Berat - - Peraikan Jalan"},
        {kode: "LCTR14", kerja: "Alokasi Traktor Konservasi Tanah LC"},
        {kode: "LCTR15", kerja: "Alokasi Truk Konservasi Tanah LC"},
        {kode: "LCTR16", kerja: "Alokasi Excavator Konservasi Tanah LC"},
        {kode: "LCTR17", kerja: "Alokasi Bulldozer Konservasi Tanah LC"},
        {kode: "LCTR18", kerja: "Alokasi Traktor - Pengendalian Lalang"},
        {kode: "LCTR19", kerja: "Alokasi Truk - Pengendalian Lalang"},
        {kode: "LCTR20", kerja: "Alokasi Pompa Air - Pengendalian Lalang"},
        {kode: "LCTR21", kerja: "Alokasi Traktor - Cincang, Perun"},
        {kode: "LCTR22", kerja: "Alokasi Truk - Cincang, Perun"},
        {kode: "LCTR23", kerja: "Alokasi Excavator - Cincang, Perun"},
        {kode: "LCTR24", kerja: "Alokasi Bulldozer - Cincang, Perun"},
        {kode: "LCTR25", kerja: "Alokasi Alat Pemotong u/ Cincang, Perun"},
        {kode: "LCTR26", kerja: "Alokasi Excavator - Buat Parit"},
        {kode: "LCTR27", kerja: "Alokasi Traktor - Survey"},
        {kode: "LCTR28", kerja: "Alokasi Truk - Survey"},
        {kode: "LCTR29", kerja: "Alokasi Jeep - Survey"},
        {kode: "LCTR30", kerja: "Alokasi Alat Pemotong u/ Tumbang"}
      ],
      "TANAM": [
        {kode: "TNJJ01", kerja: "Perbaikan Jalan Jembatan"},
        {kode: "TNMD01", kerja: "Mandor Tanam"},
        {kode: "TNBB01", kerja: "Bahan dan Langsir Bibit"},
        {kode: "TNM01", kerja: "Pancang Tanam"},
        {kode: "TNM02", kerja: "Pembuatan Lobang"},
        {kode: "TNM03", kerja: "Tabur Pupuk Lobang"},
        {kode: "TNM04", kerja: "Tanam"},
        {kode: "TNM05", kerja: "Konsolidasi Pokok"},
        {kode: "TNKC01", kerja: "Tabur Kapur Pertanian"},
        {kode: "TNKC02", kerja: "Tanam biji campuran"},
        {kode: "TNKC03", kerja: "Tanam Calopogonium caeruleum"},
        {kode: "TNKC04", kerja: "Tanam Mucuna cochichinensis"},
        {kode: "TNKC05", kerja: "Tanam Biji/stek Mucuna bracteata"},
        {kode: "TNKC06", kerja: "Pemeliharaan Biji/stek Mucuna bracteata"},
        {kode: "TNKC07", kerja: "Tanam Mucuna bracteata"},
        {kode: "TNKC08", kerja: "Tabur pupuk dasar Mucuna bracteata"},
        {kode: "TNTR01", kerja: "Alokasi Traktor/Pompong Trns Karyawan"},
        {kode: "TNTR02", kerja: "Alokasi Truk/Kendaraan Trns Karyawan"},
        {kode: "TNTR03", kerja: "Alokasi Traktor/Pompong Trns Material/Pupuk"},
        {kode: "TNTR04", kerja: "Alokasi Truk/Kendaraan Trns Material/Pupuk"},
        {kode: "TNTR05", kerja: "Alokasi Traktor Angkut Bibit Dalam Kebun"},
        {kode: "TNTR06", kerja: "Alokasi Truk Angkut Bibit Dalam Kebun"},
        {kode: "TNTR07", kerja: "Alokasi Truk Angkut Bibit Luar Kebun"},
        {kode: "TNTR08", kerja: "Alokasi Traktor Jalan/Jembatan"},
        {kode: "TNTR09", kerja: "Alokasi Truk/Pikup Jalan/Jembatan"},
        {kode: "TNTR10", kerja: "Alokasi Excavator Jalan/Jembatan"},
        {kode: "TNTR11", kerja: "Alokasi Road Greder Jalan/Jembatan"},
        {kode: "TNTR12", kerja: "Alokasi Bulldozer Jalan/Jembatan"},
        {kode: "TNTR13", kerja: "Alokasi Alat Berat Bekoloader Jalan/Jembatan"},
        {kode: "TNTR14", kerja: "Alokasi Alat Berat Jalan/Jembatan"},
        {kode: "TNAP01", kerja: "Alat Perkakas"}
      ],
      "TANAMAN BELUM MENGHASILKAN": [
        {kode: "TBTK01", kerja: "Tabur Kapur Pertanian"},
        {kode: "TBTK02", kerja: "Tanam biji campuran"},
        {kode: "TBTK03", kerja: "Tanam Calopogonium caeruleum"},
        {kode: "TBTK04", kerja: "Tanam Mucuna cochichinensis"},
        {kode: "TBTK05", kerja: "Tanam Biji/Stek Mucuna Bracteata"},
        {kode: "TBTK06", kerja: "Pelihara Biji/Stek Mucuna Bracteata"},
        {kode: "TBTK07", kerja: "Tanam Mucuna bracteata"},
        {kode: "TBTK08", kerja: "Tabur pupuk dasar Mucuna Bracteata"},
        {kode: "TBLO01", kerja: "Konsolidasi Pokok"},
        {kode: "TBBT01", kerja: "Bahan dan Langsir Bibit"},
        {kode: "TBSS01", kerja: "Pancang Sisipan"},
        {kode: "TBSS02", kerja: "Lobang & Tanam Sisipan"},
        {kode: "TBSS03", kerja: "Tabur Pupuk Lobang"},
        {kode: "TBPR01", kerja: "Garuk piringan"},
        {kode: "TBPR02", kerja: "Tarik kacangan"},
        {kode: "TBPR03", kerja: "Buka pasar pikul"},
        {kode: "TBPR04", kerja: "Buat/rawat pasar pikul Contour"},
        {kode: "TBPR05", kerja: "Buat tangga jalan panen"},
        {kode: "TBPR06", kerja: "Buat/rawat TPH"},
        {kode: "TBPR07", kerja: "Cincang guling batang"},
        {kode: "TBPR08", kerja: "Semprot piringan, pasar pikul &TPH"},
        {kode: "TBPR09", kerja: "Penomoran TPH"},
        {kode: "TBPG01", kerja: "Dangir Kacangan"},
        {kode: "TBPG02", kerja: "Dongkel anak kayu"},
        {kode: "TBPG03", kerja: "Basmi Keladi & Pisang"},
        {kode: "TBPG04", kerja: "Membabat semak"},
        {kode: "TBPG05", kerja: "Semprot pakis"},
        {kode: "TBPG06", kerja: "Semprot semak"},
        {kode: "TBPG07", kerja: "Tarik Mikania Mikranta"},
        {kode: "TBLL01", kerja: "Semprot lalang"},
        {kode: "TBLL02", kerja: "Wiping lalang"},
        {kode: "TBHP01", kerja: "Deteksi Hama&Penyakit"},
        {kode: "TBHP02", kerja: "Sensus Hama&Penyakit"},
        {kode: "TBHP03", kerja: "Semprot Hama pemakan daun"},
        {kode: "TBHP04", kerja: "Kutip Ulat / telur ulat"},
        {kode: "TBHP05", kerja: "Manual Buru Oryctes"},
        {kode: "TBHP06", kerja: "Semprot Oryctes"},
        {kode: "TBHP07", kerja: "Semprot Tirataba mundella"},
        {kode: "TBHP08", kerja: "Semprot Marasmius"},
        {kode: "TBHP09", kerja: "Semprot Rayap"},
        {kode: "TBHP10", kerja: "Buru sarang rayap"},
        {kode: "TBHP11", kerja: "Basmi Ganoderma"},
        {kode: "TBHP12", kerja: "Bongkar pokok abnormal"},
        {kode: "TBHP13", kerja: "Semprot Penyakit Daun"},
        {kode: "TBHP14", kerja: "Berantas Hama Penyakit Lain"},
        {kode: "TBHP15", kerja: "Tanam & Rawat Tanaman Inang"},
        {kode: "TBHB01", kerja: "Sensus serangan hama binatang"},
        {kode: "TBHB02", kerja: "Pasang umpan racun tikus"},
        {kode: "TBHB03", kerja: "Pasang pagar listrik gajah"},
        {kode: "TBHB04", kerja: "Buat rumah jaga pagar listrik"},
        {kode: "TBHB05", kerja: "Jaga pagar listrik"},
        {kode: "TBHB06", kerja: "Rawat pagar listrik"},
        {kode: "TBHB07", kerja: "Pasang umpan racun babi"},
        {kode: "TBHB08", kerja: "Pasang & rawat patok individu babi"},
        {kode: "TBHB09", kerja: "Pasang & rawat pagar keliling babi"},
        {kode: "TBHB10", kerja: "Buru babi"},
        {kode: "TBHB11", kerja: "Buat Gupon Tito Alba"},
        {kode: "TBHB12", kerja: "Pelihara Tito Alba"},
        {kode: "TBHB13", kerja: "Konsol pokok ex serangan binatang"},
        {kode: "TBHB14", kerja: "Hama Binatang - Ternak"},
        {kode: "TBKT01", kerja: "Buat tapak kuda"},
        {kode: "TBKT02", kerja: "Pancang rencana teras contour"},
        {kode: "TBKT03", kerja: "Buat teras contour"},
        {kode: "TBKT04", kerja: "Jaga alat berat di lapangan"},
        {kode: "TBKT05", kerja: "Rehabilitasi tapak kuda"},
        {kode: "TBKT06", kerja: "Rehabilitasi teras contour"},
        {kode: "TBKT07", kerja: "Buat & rawat rorak"},
        {kode: "TBDR01", kerja: "Pekerjaan Bendungan"},
        {kode: "TBDR02", kerja: "Buat parit"},
        {kode: "TBDR03", kerja: "Cuci parit manual"},
        {kode: "TBDR04", kerja: "Jaga alat berat sendiri di lapangan"},
        {kode: "TBDR05", kerja: "Semprot Parit"},
        {kode: "TBJJ01", kerja: "Jaga alat brt sendiri dilapangan"},
        {kode: "TBJJ02", kerja: "Pasang Gorong-gorong"},
        {kode: "TBJJ03", kerja: "Buat jembatan kayu"},
        {kode: "TBJJ04", kerja: "Rawat jalan manual"},
        {kode: "TBJJ05", kerja: "Semprot jalan"},
        {kode: "TBJJ06", kerja: "Perbaikan jembatan kayu"},
        {kode: "TBJJ07", kerja: "Pengerasan Jalan"},
        {kode: "TBJJ08", kerja: "Buat Jembatan Permanen"},
        {kode: "TBJJ09", kerja: "Buat box culvert"},
        {kode: "TBMG01", kerja: "Pemagaran"},
        {kode: "TBSN01", kerja: "Sanitasi"},
        {kode: "TBSN02", kerja: "Penyerbukan"},
        {kode: "TBSN03", kerja: "Kastrasi"},
        {kode: "TBTP01", kerja: "Pasang titi panen Kayu"},
        {kode: "TBTP02", kerja: "Pasang titi panen Beton"},
        {kode: "TBTP03", kerja: "Ecer / Bongkar titipanen"},
        {kode: "TBTS01", kerja: "Sensus pokok"},
        {kode: "TBTS02", kerja: "Penomoran pokok"},
        {kode: "TBTS03", kerja: "Buat & rawat tanda block"},
        {kode: "TBTS04", kerja: "Buat & rawat tanda perbatasan divisi"},
        {kode: "TBTS05", kerja: "Sensus pokok tata ruang kapling"},
        {kode: "TBTS06", kerja: "Buat tanda batas kapling"},
        {kode: "TBTS07", kerja: "Sensus pokok penilaian kapling"},
        {kode: "TBTS08", kerja: "Jaga Api"},
        {kode: "TBTS09", kerja: "Bongkar Pokok Abnormal"},
        {kode: "TBTS10", kerja: "Sensus Pohon tidak Produktif"},
        {kode: "TBTS11", kerja: "Tes kontaminasi Dura"},
        {kode: "TBTS12", kerja: "Ukur Panjang Pelepah"},
        {kode: "TBMD01", kerja: "Mandor Perawatan"},
        {kode: "TBMD02", kerja: "Jaga Api"},
        {kode: "TBPK01", kerja: "Tabur pupuk kacangan campuran"},
        {kode: "TBPK02", kerja: "Tabur pupuk mucuna bracteata"},
        {kode: "TBPP01", kerja: "Tabur pupuk kelapa sawit"},
        {kode: "TBPP02", kerja: "Until Pupuk"},
        {kode: "TBPP03", kerja: "Jaga pupuk"},
        {kode: "TBPP04", kerja: "Bongkar muat pupuk"},
        {kode: "TBPP05", kerja: "Ecer janjang kosong"},
        {kode: "TBPP06", kerja: "Operator LA"},
        {kode: "TBPP07", kerja: "Rawat lokasi LA"},
        {kode: "TBPP08", kerja: "Pemel. Instalasi LA"},
        {kode: "TBPP09", kerja: "Cuci / Keduk bed LA"},
        {kode: "TBTR01", kerja: "Alokasi Traktor/Pompong Trns Material"},
        {kode: "TBTR02", kerja: "Alokasi Truk/Kendaraan Trns Material"},
        {kode: "TBTR03", kerja: "Alokasi Traktor/Pompong Trns Karyawan"},
        {kode: "TBTR04", kerja: "Alokasi Kendaraan Trns Karyawan"},
        {kode: "TBTR05", kerja: "Alokasi Traktor Angkut bibit dlm Est"},
        {kode: "TBTR06", kerja: "Alokasi Truk Angkut Bibit Dalam Kebun"},
        {kode: "TBTR07", kerja: "Alokasi Truk Angkut Bibit Luar Kebun"},
        {kode: "TBTR08", kerja: "Alokasi Mist Blower"},
        {kode: "TBTR09", kerja: "Alokasi Alat Berat - Hama Penyakit"},
        {kode: "TBTR10", kerja: "Alokasi Traktor Drainage"},
        {kode: "TBTR11", kerja: "Alokasi Truk Drainage"},
        {kode: "TBTR12", kerja: "Alokasi Excavator Drainage"},
        {kode: "TBTR13", kerja: "Alokasi Alat Berat Bekoloader Drainage"},
        {kode: "TBTR14", kerja: "Alokasi Bulldozer lumut cuci kanal"},
        {kode: "TBTR15", kerja: "Alokasi Traktor Jalan/Jembatan"},
        {kode: "TBTR16", kerja: "Alokasi Truk/Pikup Jalan/Jembatan"},
        {kode: "TBTR17", kerja: "Alokasi Excavator Jalan/Jembatan"},
        {kode: "TBTR18", kerja: "Alokasi Road Greder Jalan/Jembatan"},
        {kode: "TBTR19", kerja: "Alokasi Bulldozer Jalan/Jembatan"},
        {kode: "TBTR20", kerja: "Alokasi Alat Berat Bekoloader Jalan/Jembatan"},
        {kode: "TBTR21", kerja: "Alokasi Alat Berat Jalan/Jembatan"},
        {kode: "TBTR22", kerja: "Alokasi Traktor Konservasi Tanah"},
        {kode: "TBTR23", kerja: "Alokasi Truk Konservasi Tanah"},
        {kode: "TBTR24", kerja: "Alokasi Excavator Konservasi Tanah"},
        {kode: "TBTR25", kerja: "Alokasi Bulldozer Konservasi Tanah"},
        {kode: "TBTR26", kerja: "Alokasi Bekoloader Konservasi Tanah"},
        {kode: "TBTR27", kerja: "Alokasi Pemotong Btg/Babat/rawat Pasar Pikul"},
        {kode: "TBTR28", kerja: "Alokasi Traktor Angkut pupuk"},
        {kode: "TBTR29", kerja: "Alokasi Truk Angkut pupuk"},
        {kode: "TBTR30", kerja: "Alokasi Excavator Muat & angkut Abu Janjangan"},
        {kode: "TBTR31", kerja: "Alokasi Wheel Loader Muat & angkut Abu Janjangan"},
        {kode: "TBTR32", kerja: "Alokasi Traktor Muat & angkut Abu Janjangan"},
        {kode: "TBTR33", kerja: "Alokasi Truk Muat & angkut Abu Janjangan'"},
        {kode: "TBTR34", kerja: "Alokasi Alat Berat/Mesin u/ Titi Panen"},
        {kode: "TBTR35", kerja: "Alokasi Kendaraan untuk Titi Panen"},
        {kode: "TBTR36", kerja: "Alokasi Post Hold Digger"},
        {kode: "TBAP01", kerja: "Alat Perkakas"}
      ],
      "TANAMAN MENGHASILKAN": [
        {kode: "TMBB01", kerja: "Muat Langsir Bibit"},
        {kode: "TMSB01", kerja: "Penyerbukan"},
        {kode: "TMSB02", kerja: "Pollen Collection"},
        {kode: "TMHB01", kerja: "Sensus serangan hama binatang"},
        {kode: "TMHB02", kerja: "Pasang umpan racun tikus"},
        {kode: "TMHB03", kerja: "Jaga pagar listrik"},
        {kode: "TMHB04", kerja: "Rawat pagar listrik"},
        {kode: "TMHB05", kerja: "Pasang umpan racun babi"},
        {kode: "TMHB06", kerja: "Pasang & rawat patok individu babi si"},
        {kode: "TMHB07", kerja: "Buru babi"},
        {kode: "TMHB08", kerja: "Buat Gupon Tito Alba"},
        {kode: "TMHB09", kerja: "PelihaTito Alba"},
        {kode: "TMHB10", kerja: "Konsol pokok ex serangan binatang"},
        {kode: "TMHB11", kerja: "Ecer Klerat / Simrat"},
        {kode: "TMWT01", kerja: "Pesawat-Muat&bongkar pupuk ke Bin"},
        {kode: "TMWT02", kerja: "Pesawat-Tuang & Ayak pupuk di Bin"},
        {kode: "TMWT03", kerja: "Pesawat-Memecah pupuk yang menggumpal"},
        {kode: "TMWT04", kerja: "Pesawat- Kumpulkan goni pupuk"},
        {kode: "TMWT05", kerja: "Peswt-Jaga pupuk&tutup Bin bila hujan"},
        {kode: "TMWT06", kerja: "Tabur pupuk pesawat"},
        {kode: "TMHP01", kerja: "Deteksi Hama & Penyakit"},
        {kode: "TMHP02", kerja: "Sensus Hama & Penyakit"},
        {kode: "TMHP03", kerja: "Semprot Hama pemakan daun"},
        {kode: "TMHP04", kerja: "Kutip Ulat / telur ulat"},
        {kode: "TMHP05", kerja: "Semprot Tirataba mundella"},
        {kode: "TMHP06", kerja: "Semprot Marasmius"},
        {kode: "TMHP07", kerja: "Semprot Rayap"},
        {kode: "TMHP08", kerja: "Buru sarang rayap"},
        {kode: "TMHP09", kerja: "Basmi Ganoderma"},
        {kode: "TMHP10", kerja: "Bongkar pokok abnormal"},
        {kode: "TMHP11", kerja: "Semprot Hama Daun"},
        {kode: "TMHP12", kerja: "Semprot Penyakit Daun"},
        {kode: "TMHP13", kerja: "Berantas Hama & Penyakit Lain"},
        {kode: "TMHP14", kerja: "Tanam & Pelihara Tanaman Inang"},
        {kode: "TMDR01", kerja: "Pekerjaan Bendungan"},
        {kode: "TMDR02", kerja: "Keduk parit"},
        {kode: "TMDR03", kerja: "Cuci parit manual"},
        {kode: "TMDR04", kerja: "Semprot pinggiran parit"},
        {kode: "TMDR05", kerja: "Jaga alat berat sendiri di lapangan"},
        {kode: "TMJJ01", kerja: "Tunas Pohon Pinggir Jalan"},
        {kode: "TMJJ02", kerja: "Rawat jalan manual"},
        {kode: "TMJJ03", kerja: "Pasang Nestable Flange"},
        {kode: "TMJJ04", kerja: "Semprot jalan"},
        {kode: "TMJJ05", kerja: "Pasang Gorong-gorong"},
        {kode: "TMJJ06", kerja: "Buat jembatan kayu"},
        {kode: "TMJJ07", kerja: "Perbaikan jembatan kayu"},
        {kode: "TMJJ08", kerja: "Jembatan Permanenn kayu"},
        {kode: "TMJJ09", kerja: "Jembatan Besi"},
        {kode: "TMJJ10", kerja: "Pengerasan Jalan"},
        {kode: "TMJJ11", kerja: "Buat Jembatan Beton"},
        {kode: "TMJJ12", kerja: "Buat Box Culvert"},
        {kode: "TMPG01", kerja: "Dongkel anak kayu"},
        {kode: "TMPG02", kerja: "Membabat semak"},
        {kode: "TMPG03", kerja: "Basmi Keladi & Pisang"},
        {kode: "TMPG04", kerja: "Semprot pakis"},
        {kode: "TMPG05", kerja: "Semprot Semak"},
        {kode: "TMPG06", kerja: "Tanam Mucuna Bracteata"},
        {kode: "TMPR01", kerja: "Garuk piringan"},
        {kode: "TMPR02", kerja: "Tarik kacangan"},
        {kode: "TMPR03", kerja: "Buka pasar pikul"},
        {kode: "TMPR04", kerja: "Buat/rawat pasar pikul Contour"},
        {kode: "TMPR05", kerja: "Buat tangga jalan panen"},
        {kode: "TMPR06", kerja: "Cincang guling batang"},
        {kode: "TMPR07", kerja: "Buat/rawat TPH"},
        {kode: "TMPR08", kerja: "Semprot piringan, pasar pikul &TPH"},
        {kode: "TMPR09", kerja: "Semprot piringan, psr pikul & TPH CDA"},
        {kode: "TMPR10", kerja: "Buat jalan kerbau"},
        {kode: "TMPP01", kerja: "Tabur pupuk kelapa sawit"},
        {kode: "TMPP02", kerja: "Until Pupuk"},
        {kode: "TMPP03", kerja: "Jaga pupuk"},
        {kode: "TMPP04", kerja: "Bongkar muat pupuk"},
        {kode: "TMPP05", kerja: "Ecer janjang kosong"},
        {kode: "TMPP06", kerja: "Operator LA"},
        {kode: "TMPP07", kerja: "Rawat lokasi LA"},
        {kode: "TMPP08", kerja: "Pemel. Instalasi LA"},
        {kode: "TMPP09", kerja: "Cuci / Keduk bed LA"},
        {kode: "TMPP10", kerja: "Pemupukan Mekanis"},
        {kode: "TMMD01", kerja: "Mandor Perawatan"},
        {kode: "TMMD02", kerja: "Jaga Api"},
        {kode: "TMLL01", kerja: "Semprot lalang"},
        {kode: "TMLL02", kerja: "Wiping lalang"},
        {kode: "TMSS01", kerja: "Memancang"},
        {kode: "TMSS02", kerja: "Lobang & Tanam"},
        {kode: "TMSS03", kerja: "Tabur Pupuk"},
        {kode: "TMKT01", kerja: "Rehabilitasi tapak kuda"},
        {kode: "TMKT02", kerja: "Rehabilitasi teras contour"},
        {kode: "TMKT03", kerja: "Buat & rawat rorak"},
        {kode: "TMKT04", kerja: "Konsolidasi jalan angkong"},
        {kode: "TMTS01", kerja: "Sensus Pokok"},
        {kode: "TMTS02", kerja: "Penomoran pokok"},
        {kode: "TMTS03", kerja: "Buat & rawat tanda block"},
        {kode: "TMTS04", kerja: "Buat & rawat tanda perbatasan divisi"},
        {kode: "TMTS05", kerja: "Sensus pokok tata ruang kapling"},
        {kode: "TMTS06", kerja: "Buat tanda batas kapling"},
        {kode: "TMTS07", kerja: "Sensus pokok penilaian kapling"},
        {kode: "TMTS08", kerja: "Sensus produksi"},
        {kode: "TMTS09", kerja: "Racun Pokok Abnormal"},
        {kode: "TMTS10", kerja: "Bongkar Pokok Abnormal"},
        {kode: "TMTS11", kerja: "Babat rendahan galang api"},
        {kode: "TMTS12", kerja: "Semprot galang api"},
        {kode: "TMTS13", kerja: "Test kontaminasi Dura"},
        {kode: "TMTU01", kerja: "Tunas/Prunning"},
        {kode: "TMTU02", kerja: "Basmi Gulma di Batang KS"},
        {kode: "TMTP01", kerja: "Pasang titi panen Kayu"},
        {kode: "TMTP02", kerja: "Pasang titi panen Beton"},
        {kode: "TMTP03", kerja: "Ecer / Bongkar titipanen"},
        {kode: "TMTR01", kerja: "Alokasi Excavator Konservasi Tanah"},
        {kode: "TMTR02", kerja: "Alokasi Bekoloader Konservasi Tanah"},
        {kode: "TMTR03", kerja: "Alokasi Trailler Konservasi Tanah"},
        {kode: "TMTR04", kerja: "Alokasi Truck Konservasi Tanah"},
        {kode: "TMTR05", kerja: "Alokasi Berat/Pompong TrnsMaterial"},
        {kode: "TMTR06", kerja: "Alokasi Truk/Pikup TrnsMaterial"},
        {kode: "TMTR07", kerja: "Alokasi Siram A/B By. Mesin Pompa Air"},
        {kode: "TMTR08", kerja: "Alokasi A.Berat / Pompong Trns Karyawan"},
        {kode: "TMTR09", kerja: "Alokasi Truk/Pikup Trns Karyawan"},
        {kode: "TMTR10", kerja: "Alokasi Transport air material"},
        {kode: "TMTR11", kerja: "Alokasi Mist Blower"},
        {kode: "TMTR12", kerja: "Alokasi Alat Berat - Hama Penyakit"},
        {kode: "TMTR13", kerja: "Alokasi Truk Drainage"},
        {kode: "TMTR14", kerja: "Alokasi Excavator Drainage"},
        {kode: "TMTR15", kerja: "Alokasi Bekoloader Drainage"},
        {kode: "TMTR16", kerja: "Alokasi Mesin Pompa Air"},
        {kode: "TMTR17", kerja: "Alokasi Tractor u/ Parit"},
        {kode: "TMTR18", kerja: "Alokasi Dozer lumut cuci kanal"},
        {kode: "TMTR19", kerja: "Alokasi Traktor Jalan/jembatan"},
        {kode: "TMTR20", kerja: "Alokasi Truk/Pikup Jalan/jembatan"},
        {kode: "TMTR21", kerja: "Alokasi Excavator Jalan/jembatan"},
        {kode: "TMTR22", kerja: "Alokasi Wheel Loader Jalan/jembatan"},
        {kode: "TMTR23", kerja: "Alokasi Road Grader Jalan/jembatan"},
        {kode: "TMTR24", kerja: "Alokasi Bulldozer Jalan/jembatan"},
        {kode: "TMTR25", kerja: "Alokasi Alat Berat u/ Jalan/Jembatan"},
        {kode: "TMTR26", kerja: "Alokasi Bekoloader Jalan/jembatan"},
        {kode: "TMTR27", kerja: "Alokasi Transport air semprot gawangan"},
        {kode: "TMTR28", kerja: "Alokasi Alat Berat semprot piringan & psr"},
        {kode: "TMTR29", kerja: "Alokasi A.Berat / Mesin Babat/Rawat Pasar Pikul"},
        {kode: "TMTR30", kerja: "Alokasi Chain Saw"},
        {kode: "TMTR31", kerja: "Alokasi Transport air semprot TPH"},
        {kode: "TMTR32", kerja: "Alokasi Alat berat / Kapal tarik - Angkut"},
        {kode: "TMTR33", kerja: "Alokasi Angkut pupuk -Truk"},
        {kode: "TMTR34", kerja: "Alokasi Excavator - Muat Abu Janjangan"},
        {kode: "TMTR35", kerja: "Alokasi Alat Berat - Muat Abu Janjangan"},
        {kode: "TMTR36", kerja: "Alokasi Traktor - Muat Abu Janjangan"},
        {kode: "TMTR37", kerja: "Alokasi Truk - Muat Abu Janjangan"},
        {kode: "TMTR38", kerja: "Alokasi EBS - Ecer Abu Janjangan"},
        {kode: "TMTR39", kerja: "Alokasi Bekoloader - Muat Abu Janjangan"},
        {kode: "TMTR40", kerja: "Alokasi Traktor - Angkut karyawan"},
        {kode: "TMTR41", kerja: "Alokasi Truk - Angkut karyawan"},
        {kode: "TMTR42", kerja: "Alokasi Mist Blower - Semprot pupuk"},
        {kode: "TMTR43", kerja: "Alokasi Mixer Fer. Spreader - Menabur pup"},
        {kode: "TMTR44", kerja: "Alokasi Alat Berat - LA"},
        {kode: "TMTR45", kerja: "Alokasi Mesin Pompa Air - Pemupukan"},
        {kode: "TMTR46", kerja: "Alokasi Pesawat Traktor - Angkut pupuk"},
        {kode: "TMTR47", kerja: "Alokasi Pesawat Truk - Angkut pupuk"},
        {kode: "TMTR48", kerja: "Alokasi Pesawat Wheel Loader - Muat pupuk"},
        {kode: "TMTR49", kerja: "Alokasi Pesawat Truk Mixer - Campur pupuk"},
        {kode: "TMTR50", kerja: "Alokasi Pesawat untuk angkut Pupuk"},
        {kode: "TMTR51", kerja: "Alokasi Alat Berat/Mesin untuk Titi Panen"},
        {kode: "TMTR52", kerja: "Alokasi Kendaraan untuk Titi Panen"},
        {kode: "TMTR53", kerja: "Alokasi A.Berat Buat & Rawat Tanda Perbat"},
        {kode: "TMAP01", kerja: "Alat Perkakas"}
      ],
      "PANEN": [
        {kode: "PNKB01", kerja: "Kutip Brondolan"},
        {kode: "PNJJ01", kerja: "Potong Buah Pemanen"},
        {kode: "PNPG01", kerja: "Mandor Produksi"},
        {kode: "PNPG02", kerja: "Mandor panen"},
        {kode: "PNPG03", kerja: "Krani Produksi"},
        {kode: "PNPG04", kerja: "Mandor brondolan"},
        {kode: "PNDB01", kerja: "Mandor panen dengan kerbau"},
        {kode: "PNDB02", kerja: "Mandor brondolan dengan kerbau"},
        {kode: "PNDB03", kerja: "Krani panen dengan kerbau"},
        {kode: "PNAP01", kerja: "Alat dan Perkakas"}
      ],
      "PANEN TRANSPORT": [
        {kode: "TRPT01", kerja: "Krani transport"},
        {kode: "TRPT02", kerja: "Ikat & Buka Net , lapis TPH"},
        {kode: "TRPT03", kerja: "Memuat brondolan"},
        {kode: "TRPT04", kerja: "Pemuatan Manual"},
        {kode: "TRPT05", kerja: "Pasang & Kumpul lapis TPH"},
        {kode: "TRPT06", kerja: "Manual Langsir Buah"},
        {kode: "TRPN01", kerja: "Alokasi Truk Angkut TBS"},
        {kode: "TRPN02", kerja: "Alokasi Transport Langsir TBS"},
        {kode: "TRPN03", kerja: "Alokasi Alat berat / Kapal Tarik Angkut T"},
        {kode: "TRPN04", kerja: "Alokasi Traktor Angkut TBS"},
        {kode: "TRPN05", kerja: "Alokasi Crane Truk Transport TBS"},
        {kode: "TRPN06", kerja: "Alokasi Transport truk TBS - Pihak Ke - 3"},
        {kode: "TRPN07", kerja: "Alokasi Transport alat berat TBS - Pihak ke - 3"},
        {kode: "TRPN08", kerja: "Alokasi Transport traktor TBS - Pihak ke - 3"}
      ]
    };
